# Generated by Django 4.1.2 on 2022-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='discounts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
