# Generated by Django 4.1.2 on 2022-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
