# Generated by Django 4.1.2 on 2022-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='UserCompany Unique'),
        ),
    ]
