# Generated by Django 4.1.2 on 2022-11-02 11:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_review_usercompany unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='b_phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
