# Generated by Django 4.1.2 on 2022-11-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_remove_branch_b_phone_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
