# Generated by Django 4.1.2 on 2022-11-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0005_alter_company_name_alter_cuisine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
