# Generated by Django 4.1.2 on 2022-11-08 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_alter_cuisine_options_branch_branch_location_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_country_index',
        ),
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_city_index',
        ),
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_discounts_index',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_name_index',
        ),
        migrations.RemoveIndex(
            model_name='cuisine',
            name='cuisine_name_index',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_rating_index',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_date_joined_index',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_is_active_index',
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(db_index=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.CharField(db_index=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='branch',
            name='discounts',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(db_index=True, max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
