# Generated by Django 4.1.2 on 2022-11-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0012_cuisine_company_alter_favorite_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='company',
        ),
        migrations.AddField(
            model_name='cuisine',
            name='companies',
            field=models.ManyToManyField(related_name='cuisines', related_query_name='cuisine', through='maker.CompanyCuisine', to='maker.company'),
        ),
        migrations.AlterField(
            model_name='companycuisine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_companies', to='maker.company'),
        ),
        migrations.AlterField(
            model_name='companycuisine',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_cuisines', to='maker.cuisine'),
        ),
    ]
